### ISSUE TITLE
minor issue

### ISSUE THREAD

**Issue by westwq** [MAD11877/mad21-practical-2---android-activity-LongTeck#2]
https://github.com/MAD11877/mad21-practical-2---android-activity-LongTeck/blob/8ec594e48ee672bfd9fceae6e805fd3d6ade4767/app/src/main/java/sg/edu/np/mad/madpractical/MainActivity.java#L14-L17
Need to initialise the textview with the values from User object

**Comment by LongTeck** [comment]
Initialized the textview
